name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Build and test MY kubsh and create MY deb
        run: |
          docker run --privileged \
            -v $(pwd):/mnt \
            lolopopikop/kubsh_test:local /bin/bash -c "
              set -e
              cd /mnt

              make

              cp /opt/check.sh ./check.sh
              chmod +x check.sh
              ./check.sh

              test -f kubsh.deb
            "

      - name: Upload MY kubsh.deb
        uses: actions/upload-artifact@v4
        with:
          name: kubsh-deb
          path: kubsh.deb
