name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Build, test and create kubsh.deb in Docker
        run: |
          docker run --privileged \
            -v $(pwd):/mnt \
            lolopopikop/kubsh_test:local /bin/bash -c "
              set -e
              cd /mnt

              echo '== Build kubsh =='
              make

              echo '== Run tests (check.sh) =='
              chmod +x check.sh
              ./check.sh

              echo '== Verify kubsh.deb =='
              ls -l kubsh.deb
            "

      - name: Upload kubsh.deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubsh-deb
          path: kubsh.deb
